### PR TITLE
Updating build system for GF

### PR DESCRIPTION
**Pull request by aaronbell**
Updated the repository to build using GF's standard builder tool. Also updated font data to address FB issues.

### CODE REVIEW

**Comment by hfhchan** [comment]
The thing is, the original author doesn't have glyphs, so whenever he makes a change and re-export the UFO from the `.fcp` file he is using, all of the changes made to the .UFO files will be overwritten.

Any changes made to the .UFO font files needs to be done as part of the build phase and shouldn't be committed back to the repository.

**Comment by aaronbell** [comment]
Can't he re-import the UFO back into Font Creator and then continue work from there? Otherwise the `.UFO` is not acting as a true source in this case but an interim build step.

**Comment by laubonghaudoi** [comment]
@aaronbell As far as I know, the original font creator doesn't have source files at all. He created the font by directly editing the .otf file. So the `.otf` is the only source. Even the `.ufo` files are later exported from the otf.

**Comment by MoonlitOwen** [comment]
I'm sorry, but to be honest I don't understand what this change is, also I have no idea what you are talking about. ^^;;;;;;;
When I create/edit fonts, I open the otf or ttf file directly, edit the font in the font editing software (like FontCreator or FontForge), and then output it back to otf or ttf file. 
If I want to create new fonts, or want to edit the previous font files, I do it in the font editing software directly. 
I've already output the "ufo files" in the font software and upload them on github according to your request before. 
I will continue to use my font software to output otf or ttf when I modify the fonts in the future, I don't want my right to create fonts to be restricted. 
I will output the "ufo files" again and upload them again evereytime I edit this font if you wish.
I don't know if I can respond to you in this way? Thank you.

**Comment by aaronbell** [comment]
Thanks for the information. In discussing with my colleagues, it sounds like it would be best for us to maintain a separate fork of the font at this time with the source set up as a `UFO`. We'll let you know of any issues that we discover that we'd suggest fixing upstream, and can discuss if it makes sense to re-merge the repositories at a later point.

**Comment by hfhchan** [comment]
> Can't he re-import the UFO back into Font Creator and then continue work from there?

Yes, but I am quite sure that Font Creator will output the same or similar non-standard UFO files in the end.

> Otherwise the .UFO is not acting as a true source in this case but an interim build step.

Unfortunately the workflow that the original author is familiar with, and is able to operate, only involves Font Creator. The binary format of Font Creator is not open, so the compromise solution we could come up for him was to export the UFO every time he makes a change.

Since this font is based on Source Han Sans, and the development of Source Han Sans relies on proprietary software from Adobe, we're not able to use their workflow either.

Let me know if there are changes I can make on his behalf to make this easier to integrate downstream.

**Comment by NightFurySL2001** [comment]
@aaronbell The vertical metrics tables (`vhea`/`vmtx`) that are present in this repo's font and the UFO sources are missing in your fork (https://github.com/aaronbell/ChocolateSans), which caused uneven vertical spacing issue when using the Google Font version. LXGW WenKai TC on Google Fonts does not have the issue as the `vhea`/`vmtx` tables are present.

image
image

**Pull request closed without merging**
